###

POST http://localhost:8002/participant/login
Content-Type: application/json

{
  "telNum": "12345678",
  "password": "123456"

}
###

###
POST http://localhost:8002/participant/signup
Content-Type: application/json

{
  "name": "zzc",
  "university": "四川大学",
  "password": "123456",
  "confirmPassword": "123456",
  "telNum": "13281056878"

}

###